ci:
  autofix_prs: false
  autoupdate_schedule: monthly

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-merge-conflict
    exclude: .*\.rst
  - id: check-symlinks
  - id: check-case-conflict
  - id: check-json
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
    # For the labeler GitHub Action, labels with spaces in them must
    # be put in quotes. However, the pretty-format-yaml hook will
    # remove the quotes which will break that action, so we should not
    # run this hook on `labeler.yml`.
    exclude: .github/labeler.yml

- repo: https://github.com/pre-commit/mirrors-csslint
  rev: v1.0.5
  hooks:
  - id: csslint

- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
  - id: absolufy-imports
    exclude: docs/plasmapy_sphinx

- repo: https://github.com/mattlqx/pre-commit-search-and-replace
  rev: v1.0.5
  hooks:
  - id: search-and-replace
    exclude: changelog/.*|docs/changelog/.*

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-check-blanket-noqa
    exclude: ^docs/plasmapy_sphinx/
  - id: rst-directive-colons
  - id: rst-inline-touching-normal

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    args: [--write-changes]
    additional_dependencies:
    - tomli

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.282
  hooks:
  - id: ruff
    args: [--fix]

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort
    entry: isort
    require_serial: true
    language: python
    types:
    - python

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black

- repo: https://github.com/asottile/blacken-docs
  rev: 1.15.0
  hooks:
  - id: blacken-docs
    exclude: docs/contributing/coding_guide.rst

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
  - id: nbqa-black
  - id: nbqa-isort
    args:
    - --nbqa-mutate
