name: plasmapy

channels:
- astropy
- conda-forge

dependencies:
- python=3.10
- numpy
- scipy
- astropy >= 4.3.1
- h5py >= 3.0.0
- matplotlib >= 3.3.0
- mpmath
- pandas
- pillow
- pip
- xarray
- numba
- pip:
  - hypothesis
  - docutils
  - numpydoc
  - pytest
  - lmfit
  - pygments >= 2.11.0
  - sphinx >= 3.2.0
  - sphinx-gallery
  - sphinx-hoverxref >= 1.0.0
  - sphinx_rtd_theme >= 1.0.0
  - towncrier >= 19.2.0
  - pytest-regressions
  - notebook
  - packaging
  - wrapt >= 1.11.0
